from os import nice
my_age=int(20)
my_weight=float(5.5)
my_haircolour=str("chocolate")
my_nickname=("chocolate")
print(type(my_age))
print(type(my_weight))
print(type(my_nickname)
print(type(my_nickname))
print((game)) 
print(love)
print(success)      
print(blessing)
print(GOD IS GOOD)      
